### ISSUE TITLE
A few other reference points. 

### ISSUE THREAD

**Issue by thinkstylestudio** [domain7/dev-wiki#27]
I like that you guys have this up and in the public domain. Here are a few other ones that have caught my eye over the years. 

https://engineering.hmn.md/how-we-work/style/

https://github.com/10up/Engineering-Best-Practices

https://github.com/humanmade/coding-standards

**Comment by reubenmoes** [comment]
Thanks for the links!  

This is the place where we post the things that we've agreed to as a team so that we are all aligned on our best practices.  It's also super helpful for on boarding new team members and contractors :)

**Comment by thinkstylestudio** [comment]
Welcome.

Figured... 👍 

Let me know if you need any extra help.
